# Builds, tests and publishes to maven when a commit is pushed
name: CI Tests & Publish

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'workflows/**'
      - 'README.md'

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout for CI 🛎️'
        uses: actions/checkout@v4
      - name: 'Set up JDK 21 📦'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Build with Gradle 🏗️'
        run: ./gradlew build publish
        env:
          SNAPSHOTS_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          SNAPSHOTS_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload VelocityScoreboardAPI jar
        uses: actions/upload-artifact@v4
        with:
          name: VelocityScoreboardAPI
          path: target/VelocityScoreboardAPI-*.jar
      - name: Upload VelocityScoreboardAPI Javadocs
        uses: actions/upload-artifact@v4
        with:
          name: VelocityScoreboardAPI
          path: target/VelocityScoreboardAPI-*javadoc.jar